# Generated by Django 4.2 on 2024-09-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_attributeunit_brand_remove_product_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
