# Generated by Django 4.2 on 2024-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
