# Generated by Django 4.2 on 2024-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Worse'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Great')]),
        ),
    ]
