# Generated by Django 4.2 on 2024-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartline_total_price_cart_is_ordered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'get_latest_by': 'updated_at'},
        ),
    ]
