# Generated by Django 4.2 on 2024-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
