# Generated by Django 4.2 on 2024-09-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_post_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.post'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'not payed'), (2, 'pending'), (3, 'sent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.BigIntegerField(),
        ),
    ]
