# Generated by Django 4.2 on 2024-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_created_at_alter_order_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'not payed'), (2, 'pending'), (3, 'sent')]),
        ),
    ]
